services:
  react-app:
    build:
      context: .
      dockerfile: docker/react.Dockerfile
    volumes:
      - ./react-app:/app
      - ./react-app/node_modules:/app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    command: ["pnpm", "dev"]
    depends_on:
      - go-api

  go-api:
    build:
      context: .
      dockerfile: docker/go.Dockerfile
    volumes:
      - ./go-api:/app
    ports:
      - "8081:8081"
    command: ["go", "run", "."]

volumes:
  node_modules:
