services:
  react-app:
    build:
      context: .
      dockerfile: docker/react.Dockerfile
    volumes:
      - ./react-app:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: ["pnpm", "dev"]

  go-api:
    build:
      context: .
      dockerfile: docker/go.Dockerfile
    volumes:
      - ./go-api:/app
    ports:
      - "8081:8081"
    command: ["go", "run", "."]
